### ISSUE TITLE
capture_sudo support

### ISSUE THREAD

**Issue by robd** [kentaroi/sshkit-sudo#1]
I was wondering if it might be possible to implement a `capture_sudo` method?

I have monkey patched this as follows:

``` ruby
module SSHKit
  module Backend
    class Netssh < Printer
      def capture_sudo(*args)
        result = _execute!(:sudo, *args)
        result.full_stdout.sub(%r{^\[sudo\] password for .*\r\n}, '')
      end
    end
  end
end
```

This is quite an unpleasant implementation, but it seems to work. Is there a better way of supporting this?

**Comment by robd** [comment]
Maybe this would be a slight improvement, to trim the trailing CRLF:

``` ruby
%r{^\[sudo\] password for .*\r\n(.*)\r\n}.match(result.full_stdout).captures.first
```

**Comment by kentaroi** [comment]
Hi @robd,

Thank you very much for your suggestion.
It might be better to add `attr_accessor :stdout_after_pass` to `SSHKit::Command` and manage it in `_execute!` method, but, I think, it is essentially same as yours.

About your suggested code, it doesn't seem to work correctly when a user enters a wrong password.

Thanks,

**Comment by robd** [comment]
> It might be better to add attr_accessor :stdout_after_pass to SSHKit::Command and manage it in _execute! method

Yes, I think that would make a lot of sense, since the password lines, and wrong password is already detected there. I couldn't immediately work out what was happening [here](https://github.com/kentaroi/sshkit-sudo/blob/2f1eefef53efb9f57f732159a7d75a7f26c6fc51/lib/sshkit/sudo/backends_ext/netssh.rb#L28-39), is it something like this? (Untested):

``` ruby
case data
when /Sorry.*\stry\sagain/
  SSHKit::Sudo.password_cache[password_cache_key(cmd.host)] = nil
when /password.*:/
  key = password_cache_key(cmd.host)
  pass = SSHKit::Sudo.password_cache[key]
  unless pass
    pass = $stdin.noecho(&:gets)
    SSHKit::Sudo.password_cache[key] = pass
  end
  ch.send_data(pass)
else
  cmd.stdout_after_pass += data
end
```

**Comment by kentaroi** [comment]
Hi @robd!

Yes, it is, but have to trim the leading CRLF.

Thank you,

**Comment by robd** [comment]
Yes, of course, thanks for your help

**Comment by kentaroi** [comment]
Thanks for the issue.
I will add capture_sudo support when I have time.

Thank you,
