### ISSUE TITLE
TypeError: superclass mismatch for class Netssh

### ISSUE THREAD

**Issue by quarryman** [kentaroi/sshkit-sudo#6]
In my Gemfile 
  gem 'capistrano', '3.4.0'
  gem 'sshkit-sudo', github: 'kentaroi/sshkit-sudo'

In Capfile
require 'sshkit/sudo'

bundle exec cap -T results in 
TypeError: superclass mismatch for class Netssh in require

**Comment by kentaroi** [comment]
Thanks for notifying me, @quarryman !

Quick fix is specifying sshkit version in your Gemfile as follows:

``` ruby
gem 'sshkit', '< 1.8'
```

But, I will make this gem compatible with the latest sshkit as soon as possible.

**Comment by kentaroi** [comment]
I just released v0.1.0, which is compatible with sshkit 1.8 and later.
If you find any problems, please let me know.
Thank you.
